[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-8080} --workers 4 --timeout 120 --chdir backend app:app"
