"""Add meal planning models

Revision ID: 22d67b867bf3
Revises: 91487a363b6b
Create Date: 2025-08-27 15:40:34.438326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d67b867bf3'
down_revision = '91487a363b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('scheduled_date')

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('week_end_date', sa.Date(), nullable=False))
        batch_op.drop_column('start_date')
        batch_op.drop_column('name')
        batch_op.drop_column('end_date')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('nutrition_data', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('protein',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('carbs',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('fat',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('fiber',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sugar',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sodium',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('nutrition_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('sodium',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sugar',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('fiber',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('fat',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('protein',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('calories',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.drop_column('week_end_date')
        batch_op.drop_column('week_start_date')

    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
