"""Add meal planning models

Revision ID: 29d78e39153f
Revises: 22d67b867bf3
Create Date: 2025-08-27 16:23:24.158540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d78e39153f'
down_revision = '22d67b867bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weekly_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_cuisines', sa.Text(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('meal_planning_reminders', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('meal_plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('custom_meal_name', sa.String(length=255), nullable=True),
    sa.Column('custom_meal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['favorite_recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nutrition_data')
    op.drop_table('meal')
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_column('week_end_date')

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meal_plan_id')

    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_plan_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'meal_plan', ['meal_plan_id'], ['id'])

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_end_date', sa.DATE(), nullable=False))

    op.create_table('meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('meal_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['favorite_recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.Column('calories', sa.FLOAT(), nullable=False),
    sa.Column('protein', sa.FLOAT(), nullable=False),
    sa.Column('carbs', sa.FLOAT(), nullable=False),
    sa.Column('fat', sa.FLOAT(), nullable=False),
    sa.Column('fiber', sa.FLOAT(), nullable=False),
    sa.Column('sugar', sa.FLOAT(), nullable=False),
    sa.Column('sodium', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('meal_plan_item')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
