"""Added time breakdown to FavoriteRecipe

Revision ID: 443885990865
Revises: 9c8a5212526a
Create Date: 2025-03-12 06:17:01.983338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443885990865'
down_revision = '9c8a5212526a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_breakdown', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('facebook_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_facebook_id'), ['facebook_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.drop_index(batch_op.f('ix_user_facebook_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('facebook_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('google_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.drop_column('time_breakdown')

    # ### end Alembic commands ###
