"""Update user with google auth

Revision ID: 453cd6cb6733
Revises: 443885990865
Create Date: 2025-03-12 07:13:26.374038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453cd6cb6733'
down_revision = '443885990865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
