"""Added time and nutritional value to FavoriteRecipe

Revision ID: 9c8a5212526a
Revises: 1913cb1cde78
Create Date: 2025-03-11 12:00:49.361893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8a5212526a'
down_revision = '1913cb1cde78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nutritional_value', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.drop_column('nutritional_value')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
